"""Add loan_custom_id to Loan model

Revision ID: 031c82c79694
Revises: fa31795b4d08
Create Date: 2026-03-11 19:10:11.542000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031c82c79694'
down_revision: Union[str, Sequence[str], None] = 'fa31795b4d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fin_loans', sa.Column('loan_custom_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_fin_loans_loan_custom_id'), 'fin_loans', ['loan_custom_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_loans_loan_custom_id'), table_name='fin_loans')
    op.drop_column('fin_loans', 'loan_custom_id')
    # ### end Alembic commands ###
