"""add_first_last_name_to_user

Revision ID: 321fb116e853
Revises: 9c514bb44ab3
Create Date: 2026-03-11 20:23:37.787251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321fb116e853'
down_revision: Union[str, Sequence[str], None] = '9c514bb44ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('core_users', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_users', 'last_name')
    op.drop_column('core_users', 'first_name')
    # ### end Alembic commands ###
