"""Add profile fields and transaction enhancements

Revision ID: 9c514bb44ab3
Revises: 07aa99790dc3
Create Date: 2026-03-11 19:47:39.257250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c514bb44ab3'
down_revision: Union[str, Sequence[str], None] = '07aa99790dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('core_users', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('fin_transactions', sa.Column('transaction_type', sa.String(length=50), nullable=False))
    op.add_column('fin_transactions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('fin_transactions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('fin_transactions', sa.Column('cheque_number', sa.String(length=50), nullable=True))
    op.add_column('fin_transactions', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('fin_transactions', sa.Column('cheque_date', sa.Date(), nullable=True))
    op.add_column('fin_transactions', sa.Column('clearance_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_fin_transactions_status'), 'fin_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_fin_transactions_transaction_type'), 'fin_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_transactions_transaction_type'), table_name='fin_transactions')
    op.drop_index(op.f('ix_fin_transactions_status'), table_name='fin_transactions')
    op.drop_column('fin_transactions', 'clearance_date')
    op.drop_column('fin_transactions', 'cheque_date')
    op.drop_column('fin_transactions', 'bank_name')
    op.drop_column('fin_transactions', 'cheque_number')
    op.drop_column('fin_transactions', 'status')
    op.drop_column('fin_transactions', 'description')
    op.drop_column('fin_transactions', 'transaction_type')
    op.drop_column('core_users', 'job_title')
    op.drop_column('core_users', 'phone_number')
    # ### end Alembic commands ###
