"""Initial migration

Revision ID: a25f0d627aec
Revises: 
Create Date: 2026-03-04 02:24:31.908717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a25f0d627aec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old Django-related tables if they exist
    tables_to_drop = [
        'clients_business', 'clients_bankingandotherloandetail', 'system_settings_loansettings',
        'clients_businessdocument', 'transactions_emischedule', 'system_settings_generalsettings',
        'loans_loan', 'clients_client', 'clients_clientkyc', 'system_settings_notificationsettings',
        'transactions_transaction', 'clients_financeconfig', 'users_passwordresetcode',
        'users_user', 'clients_financedocument'
    ]
    for table in tables_to_drop:
        op.execute(f'DROP TABLE IF EXISTS {table} CASCADE')
    op.add_column('core_users', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('core_users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('core_users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.create_index(op.f('ix_core_users_uuid'), 'core_users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_users_uuid'), table_name='core_users')
    op.drop_column('core_users', 'last_login_ip')
    op.drop_column('core_users', 'last_login_at')
    op.drop_column('core_users', 'uuid')
    op.create_table('clients_financedocument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('finance_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['finance_config_id'], ['clients_financeconfig.id'], name=op.f('clients_financedocument_finance_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_financedocument_pkey'))
    )
    op.create_index(op.f('ix_clients_financedocument_id'), 'clients_financedocument', ['id'], unique=False)
    op.create_table('users_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_user_pkey'))
    )
    op.create_index(op.f('ix_users_user_id'), 'users_user', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=True)
    op.create_table('users_passwordresetcode',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], name=op.f('users_passwordresetcode_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_passwordresetcode_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('users_passwordresetcode_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_passwordresetcode_id'), 'users_passwordresetcode', ['id'], unique=False)
    op.create_table('clients_financeconfig',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('repayment_terms', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('loan_collection_date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cutting', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('purpose_of_loan', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expected_emi_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients_client.id'], name=op.f('clients_financeconfig_client_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_financeconfig_pkey'))
    )
    op.create_index(op.f('ix_clients_financeconfig_id'), 'clients_financeconfig', ['id'], unique=False)
    op.create_table('transactions_transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emi_schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proof_document', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emi_schedule_id'], ['transactions_emischedule.id'], name=op.f('transactions_transaction_emi_schedule_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans_loan.id'], name=op.f('transactions_transaction_loan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_transaction_pkey'))
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions_transaction', ['id'], unique=False)
    op.create_table('system_settings_notificationsettings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enable_email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_gateway_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('alert_days_before_emi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_notificationsettings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_notificationsettings_id'), 'system_settings_notificationsettings', ['id'], unique=False)
    op.create_table('clients_clientkyc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aadhar_client', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('aadhar_spouse', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pan_client', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pan_spouse', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('eb_bill', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('kyc_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients_client.id'], name=op.f('clients_clientkyc_client_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_clientkyc_pkey')),
    sa.UniqueConstraint('client_id', name=op.f('clients_clientkyc_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clients_clientkyc_id'), 'clients_clientkyc', ['id'], unique=False)
    op.create_table('clients_client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('spouse_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('resident_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('alternative_mobile_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users_user.id'], name=op.f('clients_client_created_by_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], name=op.f('clients_client_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_client_pkey')),
    sa.UniqueConstraint('mobile_number', name=op.f('clients_client_mobile_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('clients_client_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients_client', ['id'], unique=False)
    op.create_table('loans_loan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('commission_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('commission_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('cutting_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('middle_man_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tenure', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emi_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('collection_date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients_client.id'], name=op.f('loans_loan_client_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('loans_loan_pkey'))
    )
    op.create_index(op.f('ix_loans_loan_id'), 'loans_loan', ['id'], unique=False)
    op.create_table('system_settings_generalsettings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('support_email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('support_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_generalsettings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_generalsettings_id'), 'system_settings_generalsettings', ['id'], unique=False)
    op.create_table('transactions_emischedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expected_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('principal_component', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_component', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance_remaining', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans_loan.id'], name=op.f('transactions_emischedule_loan_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_emischedule_pkey'))
    )
    op.create_index(op.f('ix_transactions_emischedule_id'), 'transactions_emischedule', ['id'], unique=False)
    op.create_table('clients_businessdocument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['clients_business.id'], name=op.f('clients_businessdocument_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_businessdocument_pkey'))
    )
    op.create_index(op.f('ix_clients_businessdocument_id'), 'clients_businessdocument', ['id'], unique=False)
    op.create_table('system_settings_loansettings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('maximum_loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('minimum_loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('penalty_rate_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_loansettings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_loansettings_id'), 'system_settings_loansettings', ['id'], unique=False)
    op.create_table('clients_bankingandotherloandetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['clients_business.id'], name=op.f('clients_bankingandotherloandetail_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_bankingandotherloandetail_pkey'))
    )
    op.create_index(op.f('ix_clients_bankingandotherloandetail_id'), 'clients_bankingandotherloandetail', ['id'], unique=False)
    op.create_table('clients_business',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ownership_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nature_of_business', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('visiting_card', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('annual_turnover', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('business_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_client.id'], name=op.f('clients_business_client_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_business_pkey')),
    sa.UniqueConstraint('client_id', name=op.f('clients_business_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clients_business_id'), 'clients_business', ['id'], unique=False)
    # ### end Alembic commands ###
