"""add_uuid_to_loans

Revision ID: eac94c1d79e7
Revises: 69cdf694c9df
Create Date: 2026-03-31 16:55:42.917099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac94c1d79e7'
down_revision: Union[str, Sequence[str], None] = '69cdf694c9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import uuid
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('fin_loan_applications', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('fin_loans', sa.Column('uuid', sa.String(length=36), nullable=True))

    # 2. Backfill existing rows with random UUIDs
    connection = op.get_bind()
    
    # Backfill fin_loan_applications
    rows = connection.execute(sa.text("SELECT id FROM fin_loan_applications")).fetchall()
    for row in rows:
        connection.execute(
            sa.text("UPDATE fin_loan_applications SET uuid = :uuid WHERE id = :id"),
            {"uuid": str(uuid.uuid4()), "id": row.id}
        )
        
    # Backfill fin_loans
    rows = connection.execute(sa.text("SELECT id FROM fin_loans")).fetchall()
    for row in rows:
        connection.execute(
            sa.text("UPDATE fin_loans SET uuid = :uuid WHERE id = :id"),
            {"uuid": str(uuid.uuid4()), "id": row.id}
        )

    # 3. Set to non-nullable and create index
    op.alter_column('fin_loan_applications', 'uuid', nullable=False)
    op.create_index(op.f('ix_fin_loan_applications_uuid'), 'fin_loan_applications', ['uuid'], unique=True)
    
    op.alter_column('fin_loans', 'uuid', nullable=False)
    op.create_index(op.f('ix_fin_loans_uuid'), 'fin_loans', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fin_loans_uuid'), table_name='fin_loans')
    op.drop_column('fin_loans', 'uuid')
    op.drop_index(op.f('ix_fin_loan_applications_uuid'), table_name='fin_loan_applications')
    op.drop_column('fin_loan_applications', 'uuid')
    # ### end Alembic commands ###
