"""Add status column and make fields nullable in Client

Revision ID: fa31795b4d08
Revises: 46d518821ea2
Create Date: 2026-03-11 18:52:03.175163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa31795b4d08'
down_revision: Union[str, Sequence[str], None] = '46d518821ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_business_documents_id'), table_name='core_business_documents')
    op.drop_table('core_business_documents')
    op.drop_index(op.f('ix_core_business_banking_details_id'), table_name='core_business_banking_details')
    op.drop_table('core_business_banking_details')
    op.drop_index(op.f('ix_sys_notification_settings_id'), table_name='sys_notification_settings')
    op.drop_table('sys_notification_settings')
    op.drop_index(op.f('ix_sys_loan_settings_id'), table_name='sys_loan_settings')
    op.drop_table('sys_loan_settings')
    op.drop_index(op.f('ix_sys_general_settings_id'), table_name='sys_general_settings')
    op.drop_table('sys_general_settings')
    op.add_column('core_clients', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('core_clients', 'marital_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('core_clients', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('core_clients', 'resident_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('core_clients', 'permanent_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_core_clients_status'), 'core_clients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_clients_status'), table_name='core_clients')
    op.alter_column('core_clients', 'permanent_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_clients', 'resident_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('core_clients', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('core_clients', 'marital_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('core_clients', 'status')
    op.create_table('sys_general_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('support_email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('support_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_general_settings_pkey'))
    )
    op.create_index(op.f('ix_sys_general_settings_id'), 'sys_general_settings', ['id'], unique=False)
    op.create_table('sys_loan_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('maximum_loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('minimum_loan_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('penalty_rate_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_loan_settings_pkey'))
    )
    op.create_index(op.f('ix_sys_loan_settings_id'), 'sys_loan_settings', ['id'], unique=False)
    op.create_table('sys_notification_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enable_email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_gateway_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('alert_days_before_emi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_notification_settings_pkey'))
    )
    op.create_index(op.f('ix_sys_notification_settings_id'), 'sys_notification_settings', ['id'], unique=False)
    op.create_table('core_business_banking_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['core_businesses.id'], name=op.f('core_business_banking_details_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('core_business_banking_details_pkey'))
    )
    op.create_index(op.f('ix_core_business_banking_details_id'), 'core_business_banking_details', ['id'], unique=False)
    op.create_table('core_business_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['core_businesses.id'], name=op.f('core_business_documents_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('core_business_documents_pkey'))
    )
    op.create_index(op.f('ix_core_business_documents_id'), 'core_business_documents', ['id'], unique=False)
    # ### end Alembic commands ###
